name: Deploy Backend

on:
  push:
    paths:
      - "backend/**"
      - "frontend/**"
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build BE image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-todos ./backend
      - name: Build FE image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-todos --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} ./frontend

      - name: Push image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-todos:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-todos:latest
  pull-and-run:
    name: Pull and run image
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            CONTAINER=$(docker ps --format '{{.ID}} {{.Ports}}' | grep '0.0.0.0:3002->' | awk '{print $1}')
             if [ ! -z "$CONTAINER" ]; then
               echo "Stopping container using port 3002: $CONTAINER"
               docker stop $CONTAINER
               docker rm $CONTAINER
             fi
             docker pull ${{ secrets.DOCKER_USERNAME }}/backend-todos:latest
             docker rm -f backend-todos || true
             docker run --name backend-todos -d -p 3002:3000 ${{ secrets.DOCKER_USERNAME }}/backend-todos:latest
              
              CONTAINER=$(docker ps --format '{{.ID}} {{.Ports}}' | grep '0.0.0.0:81->' | awk '{print $1}')
             if [ ! -z "$CONTAINER" ]; then
               echo "Stopping container using port 81: $CONTAINER"
               docker stop $CONTAINER
               docker rm $CONTAINER
             fi
             docker pull ${{ secrets.DOCKER_USERNAME }}/frontend-todos:latest
             docker rm -f frontend-todos || true
             docker run --name frontend-todos -d -p 81:80 ${{ secrets.DOCKER_USERNAME }}/frontend-todos:latest
